dbt_food_delivery:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: FOHMZVX-XS05522
      user: sunil
      password: Sunil@7993385512
      role: ACCOUNTADMIN
      database: FOOD_DELIVERY_DEV
      warehouse: FOOD_DWH
      schema: public
      threads: 4