name: dbt CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  dbt-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dbt
        run: |
          pip install dbt-core dbt-snowflake

      # 👇 THIS IS WHERE YOUR BLOCK GOES
      - name: Create profiles.yml
        run: |
          mkdir -p ~/.dbt
          cat > ~/.dbt/profiles.yml <<EOF
          food_delivery_dbt:
            target: dev
            outputs:
              dev:
                type: snowflake
                account: FOHMZVX-XS05522
                user: sunil
                password: Sunil@7993385512
                role: ACCOUNTADMIN
                database: FOOD_DELIVERY_DB
                warehouse: FOOD_DWH
                schema: staging_dev
                threads: 4
          EOF

      - name: Run dbt deps
        working-directory: food_delivery_dbt
        run: dbt deps

      - name: Run dbt models
        working-directory: food_delivery_dbt
        run: dbt run

      - name: Run dbt tests
        working-directory: food_delivery_dbt
        run: dbt test